

export var mydata={
    interviewstatuss:[
        {
            value: '1',
            label: '招待された'
          }, {
            value: '2',
            label: '面接を受けた'
          }, 
          {
            value: '3',
            label: '面接を断った'
          },
          {
            value: '4',
            label: '結果まち'
          }, {
            value: '5',
            label: '合格'
          }, {
            value: '6',
            label: '不合格'
          }, {
            value: '7',
            label: '面接がキャンセルされた'
          }, {
            value: '8',
            label: '面接参加をキャンセルした'
          }, {
            value: '9',
            label: '合格を辞退した'
          }
    
    ],
    textsLan:["知識あり","簡単なプログラミングができる","一人でアプリケーション開発できる","業務で即戦力になれる","メンバー指導できる",""],
    textsDB:["知識あり","簡単なSELECT文が書ける","SQLを使ったプログラミングができる","システムの要件に応じてテーブル設計できる","メインPG/メンターとして，主設計を任せられる",""],
    textsOS:["知識あり","基本操作ができる","インストールから基本設定までできる","システムデザイン、ネットワーク構築できる","トラブルシューティング、キャパシティプランニングができる",""],
    
    japanese:[
        {value:'ネイテイブ',label:'ネイテイブ'},
        {value:'N1',label:'N1'},
        {value:'N2',label:'N2'},
        {value:'N3',label:'N3'},
        {value:'N4',label:'N4'},
        {value:'N5',label:'N5'},
    ],
    industryList:[{value:'建設業',label:'建設業'},
                                {value:'製造業',label:'製造業'},
                                {value:'電気･ガス･熱供給･水道業',label:'電気･ガス･熱供給･水道業'},
                                {value:'情報通信業',label:'情報通信業'},
                                {value:'運輸業',label:'運輸業'},
                                {value:'郵便業',label:'郵便業'},
                                {value:'卸売業',label:'卸売業'},
                                {value:'小売業',label:'小売業'},
                                {value:'金融業',label:'金融業'},
                                {value:'保険業',label:'保険業'},
                                {value:'不動産業',label:'不動産業'},
                                {value:'物品賃貸業',label:'物品賃貸業'},
                                {value:'学術研究､専門･技術サービス業',label:'学術研究､専門･技術サービス業'},
                                {value:'宿泊業',label:'宿泊業'},
                                {value:'飲食サービス業',label:'飲食サービス業'},
                                {value:'生活関連サービス業',label:'生活関連サービス業'},
                                {value:'娯楽業',label:'娯楽業'},
                                {value:'教育､学習支援業',label:'教育､学習支援業'},
                                {value:'医療',label:'医療'},
                                {value:'福祉',label:'福祉'},
                                {value:'複合サービス事業',label:'複合サービス事業'},
                                {value:'サービス業',label:'サービス業'},
                                {value:'公務',label:'公務'},
                                {value:'農業',label:'農業'},
                                {value:'林業',label:'林業'},
                                {value:'漁業',label:'漁業'},
                                {value:'鉱業',label:'鉱業'},
                                {value:'採石業',label:'採石業'},
                                {value:'砂利採取業',label:'砂利採取業'},],

countris:[{value:'日本',label:'日本'},
                    {value:'中国',label:'中国'},
                    {value:'韓国',label:'韓国'},
                    {value:'中国(台湾)',label:'中国(台湾)'},
                    {value:'インド',label:'インド'},
                    {value:'米国',label:'米国'},
                    {value:'アイスランド',label:'アイスランド'},
                    {value:'アイルランド',label:'アイルランド'},
                    {value:'アゼルバイジャン',label:'アゼルバイジャン'},
                    {value:'アフガニスタン',label:'アフガニスタン'},
                    {value:'アラブ首長国連邦',label:'アラブ首長国連邦'},
                    {value:'アルジェリア',label:'アルジェリア'},
                    {value:'アルゼンチン',label:'アルゼンチン'},
                    {value:'アルバニア',label:'アルバニア'},
                    {value:'アルメニア',label:'アルメニア'},
                    {value:'アンゴラ',label:'アンゴラ'},
                    {value:'アンティグア・バーブーダ',label:'アンティグア・バーブーダ'},
                    {value:'アンドラ',label:'アンドラ'},
                    {value:'イエメン',label:'イエメン'},
                    {value:'イスラエル',label:'イスラエル'},
                    {value:'イタリア',label:'イタリア'},
                    {value:'イラク',label:'イラク'},
                    {value:'イラン',label:'イラン'},
                    {value:'インドネシア',label:'インドネシア'},
                    {value:'ウガンダ',label:'ウガンダ'},
                    {value:'ウクライナ',label:'ウクライナ'},
                    {value:'ウズベキスタン',label:'ウズベキスタン'},
                    {value:'ウルグアイ',label:'ウルグアイ'},
                    {value:'英国',label:'英国'},
                    {value:'エクアドル',label:'エクアドル'},
                    {value:'エジプト',label:'エジプト'},
                    {value:'エストニア',label:'エストニア'},
                    {value:'エスワティニ',label:'エスワティニ'},
                    {value:'エチオピア',label:'エチオピア'},
                    {value:'エリトリア',label:'エリトリア'},
                    {value:'エルサルバドル',label:'エルサルバドル'},
                    {value:'オーストラリア',label:'オーストラリア'},
                    {value:'オーストリア',label:'オーストリア'},
                    {value:'オマーン',label:'オマーン'},
                    {value:'オランダ',label:'オランダ'},
                    {value:'カーボベルデ',label:'カーボベルデ'},
                    {value:'カザフスタン',label:'カザフスタン'},
                    {value:'カタール',label:'カタール'},
                    {value:'カナダ',label:'カナダ'},
                    {value:'カメルーン',label:'カメルーン'},
                    {value:'カンボジア',label:'カンボジア'},
                    {value:'ガーナ',label:'ガーナ'},
                    {value:'ガイアナ',label:'ガイアナ'},
                    {value:'ガボン',label:'ガボン'},
                    {value:'ガンビア',label:'ガンビア'},
                    {value:'北マケドニア',label:'北マケドニア'},
                    {value:'キプロス',label:'キプロス'},
                    {value:'キューバ',label:'キューバ'},
                    {value:'キリバス',label:'キリバス'},
                    {value:'キルギス',label:'キルギス'},
                    {value:'ギニア',label:'ギニア'},
                    {value:'ギニアビサウ',label:'ギニアビサウ'},
                    {value:'ギリシャ',label:'ギリシャ'},
                    {value:'クウェート',label:'クウェート'},
                    {value:'クック諸島',label:'クック諸島'},
                    {value:'クロアチア',label:'クロアチア'},
                    {value:'グアテマラ',label:'グアテマラ'},
                    {value:'グレナダ',label:'グレナダ'},
                    {value:'ケニア',label:'ケニア'},
                    {value:'コートジボワール',label:'コートジボワール'},
                    {value:'コスタリカ',label:'コスタリカ'},
                    {value:'コソボ',label:'コソボ'},
                    {value:'コモロ',label:'コモロ'},
                    {value:'コロンビア',label:'コロンビア'},
                    {value:'コンゴ共和国',label:'コンゴ共和国'},
                    {value:'コンゴ民主共和国',label:'コンゴ民主共和国'},
                    {value:'サウジアラビア',label:'サウジアラビア'},
                    {value:'サモア',label:'サモア'},
                    {value:'サントメ・プリンシペ',label:'サントメ・プリンシペ'},
                    {value:'サンマリノ',label:'サンマリノ'},
                    {value:'ザンビア',label:'ザンビア'},
                    {value:'シエラレオネ',label:'シエラレオネ'},
                    {value:'シリア',label:'シリア'},
                    {value:'シンガポール',label:'シンガポール'},
                    {value:'ジブチ',label:'ジブチ'},
                    {value:'ジャマイカ',label:'ジャマイカ'},
                    {value:'ジョージア',label:'ジョージア'},
                    {value:'ジンバブエ',label:'ジンバブエ'},
                    {value:'スーダン',label:'スーダン'},
                    {value:'スイス',label:'スイス'},
                    {value:'スウェーデン',label:'スウェーデン'},
                    {value:'スペイン',label:'スペイン'},
                    {value:'スリナム',label:'スリナム'},
                    {value:'スリランカ',label:'スリランカ'},
                    {value:'スロバキア',label:'スロバキア'},
                    {value:'スロベニア',label:'スロベニア'},
                    {value:'セーシェル',label:'セーシェル'},
                    {value:'赤道ギニア',label:'赤道ギニア'},
                    {value:'セネガル',label:'セネガル'},
                    {value:'セルビア',label:'セルビア'},
                    {value:'セントクリストファー・ネービス',label:'セントクリストファー・ネービス'},
                    {value:'セントビンセント・グレナディーン諸島',label:'セントビンセント・グレナディーン諸島'},
                    {value:'セントルシア',label:'セントルシア'},
                    {value:'ソマリア',label:'ソマリア'},
                    {value:'ソロモン',label:'ソロモン'},
                    {value:'タイ',label:'タイ'},
                    {value:'タジキスタン',label:'タジキスタン'},
                    {value:'タンザニア',label:'タンザニア'},
                    {value:'チェコ',label:'チェコ'},
                    {value:'チャド',label:'チャド'},
                    {value:'中央アフリカ',label:'中央アフリカ'},
                    {value:'チュニジア',label:'チュニジア'},
                    {value:'チリ',label:'チリ'},
                    {value:'ツバル',label:'ツバル'},
                    {value:'デンマーク',label:'デンマーク'},
                    {value:'トーゴ',label:'トーゴ'},
                    {value:'トリニダード・トバゴ',label:'トリニダード・トバゴ'},
                    {value:'トルクメニスタン',label:'トルクメニスタン'},
                    {value:'トルコ',label:'トルコ'},
                    {value:'トンガ',label:'トンガ'},
                    {value:'ドイツ',label:'ドイツ'},
                    {value:'ドミニカ共和国',label:'ドミニカ共和国'},
                    {value:'ドミニカ国',label:'ドミニカ国'},
                    {value:'ナイジェリア',label:'ナイジェリア'},
                    {value:'ナウル',label:'ナウル'},
                    {value:'ナミビア',label:'ナミビア'},
                    {value:'ニカラグア',label:'ニカラグア'},
                    {value:'ニジェール',label:'ニジェール'},
                    {value:'ニュージーランド',label:'ニュージーランド'},
                    {value:'ネパール',label:'ネパール'},
                    {value:'ノルウェー',label:'ノルウェー'},
                    {value:'ハイチ',label:'ハイチ'},
                    {value:'ハンガリー',label:'ハンガリー'},
                    {value:'バーレーン',label:'バーレーン'},
                    {value:'バチカン',label:'バチカン'},
                    {value:'バヌアツ',label:'バヌアツ'},
                    {value:'バハマ',label:'バハマ'},
                    {value:'バルバドス',label:'バルバドス'},
                    {value:'バングラデシュ',label:'バングラデシュ'},
                    {value:'パキスタン',label:'パキスタン'},
                    {value:'パナマ',label:'パナマ'},
                    {value:'パプアニューギニア',label:'パプアニューギニア'},
                    {value:'パラオ',label:'パラオ'},
                    {value:'パラグアイ',label:'パラグアイ'},
                    {value:'パレスチナ(PLO)',label:'パレスチナ(PLO)'},
                    {value:'東ティモール',label:'東ティモール'},
                    {value:'フィジー',label:'フィジー'},
                    {value:'フィリピン',label:'フィリピン'},
                    {value:'フィンランド',label:'フィンランド'},
                    {value:'フランス',label:'フランス'},
                    {value:'ブータン',label:'ブータン'},
                    {value:'ブラジル',label:'ブラジル'},
                    {value:'ブルガリア',label:'ブルガリア'},
                    {value:'ブルキナファソ',label:'ブルキナファソ'},
                    {value:'ブルネイ・ダルサラーム',label:'ブルネイ・ダルサラーム'},
                    {value:'ブルンジ',label:'ブルンジ'},
                    {value:'ベトナム',label:'ベトナム'},
                    {value:'ベナン',label:'ベナン'},
                    {value:'ベネズエラ',label:'ベネズエラ'},
                    {value:'ベラルーシ',label:'ベラルーシ'},
                    {value:'ベリーズ',label:'ベリーズ'},
                    {value:'ベルギー',label:'ベルギー'},
                    {value:'ペルー',label:'ペルー'},
                    {value:'ホンジュラス',label:'ホンジュラス'},
                    {value:'ボスニア・ヘルツェゴビナ',label:'ボスニア・ヘルツェゴビナ'},
                    {value:'ボツワナ',label:'ボツワナ'},
                    {value:'ボリビア',label:'ボリビア'},
                    {value:'ポーランド',label:'ポーランド'},
                    {value:'ポルトガル',label:'ポルトガル'},
                    {value:'マーシャル',label:'マーシャル'},
                    {value:'マダガスカル',label:'マダガスカル'},
                    {value:'マラウイ',label:'マラウイ'},
                    {value:'マリ',label:'マリ'},
                    {value:'マルタ',label:'マルタ'},
                    {value:'マレーシア',label:'マレーシア'},
                    {value:'ミクロネシア',label:'ミクロネシア'},
                    {value:'南アフリカ',label:'南アフリカ'},
                    {value:'南スーダン',label:'南スーダン'},
                    {value:'ミャンマー',label:'ミャンマー'},
                    {value:'メキシコ',label:'メキシコ'},
                    {value:'モーリシャス',label:'モーリシャス'},
                    {value:'モーリタニア',label:'モーリタニア'},
                    {value:'モザンビーク',label:'モザンビーク'},
                    {value:'モナコ',label:'モナコ'},
                    {value:'モルディブ',label:'モルディブ'},
                    {value:'モルドバ',label:'モルドバ'},
                    {value:'モロッコ',label:'モロッコ'},
                    {value:'モンゴル',label:'モンゴル'},
                    {value:'モンテネグロ',label:'モンテネグロ'},
                    {value:'ヨルダン',label:'ヨルダン'},
                    {value:'ラオス',label:'ラオス'},
                    {value:'ラトビア',label:'ラトビア'},
                    {value:'リトアニア',label:'リトアニア'},
                    {value:'リヒテンシュタイン',label:'リヒテンシュタイン'},
                    {value:'リビア',label:'リビア'},
                    {value:'リベリア',label:'リベリア'},
                    {value:'ルーマニア',label:'ルーマニア'},
                    {value:'ルクセンブルク',label:'ルクセンブルク'},
                    {value:'ルワンダ',label:'ルワンダ'},
                    {value:'レソト',label:'レソト'},
                    {value:'レバノン',label:'レバノン'},
                    {value:'ロシア連邦',label:'ロシア連邦'},],

     cities:  [{value:'北海道',label:'北海道'},
                    {value:'青森県',label:'青森県'},
                    {value:'岩手県',label:'岩手県'},
                    {value:'宮城県',label:'宮城県'},
                    {value:'秋田県',label:'秋田県'},
                    {value:'山形県',label:'山形県'},
                    {value:'福島県',label:'福島県'},
                    {value:'茨城県',label:'茨城県'},
                    {value:'栃木県',label:'栃木県'},
                    {value:'群馬県',label:'群馬県'},
                    {value:'埼玉県',label:'埼玉県'},
                    {value:'千葉県',label:'千葉県'},
                    {value:'東京都',label:'東京都'},
                    {value:'神奈川県',label:'神奈川県'},
                    {value:'新潟県',label:'新潟県'},
                    {value:'富山県',label:'富山県'},
                    {value:'石川県',label:'石川県'},
                    {value:'福井県',label:'福井県'},
                    {value:'山梨県',label:'山梨県'},
                    {value:'長野県',label:'長野県'},
                    {value:'岐阜県',label:'岐阜県'},
                    {value:'静岡県',label:'静岡県'},
                    {value:'愛知県',label:'愛知県'},
                    {value:'三重県',label:'三重県'},
                    {value:'滋賀県',label:'滋賀県'},
                    {value:'京都府',label:'京都府'},
                    {value:'大阪府',label:'大阪府'},
                    {value:'兵庫県',label:'兵庫県'},
                    {value:'奈良県',label:'奈良県'},
                    {value:'和歌山県',label:'和歌山県'},
                    {value:'鳥取県',label:'鳥取県'},
                    {value:'島根県',label:'島根県'},
                    {value:'岡山県',label:'岡山県'},
                    {value:'広島県',label:'広島県'},
                    {value:'山口県',label:'山口県'},
                    {value:'徳島県',label:'徳島県'},
                    {value:'香川県',label:'香川県'},
                    {value:'愛媛県',label:'愛媛県'},
                    {value:'高知県',label:'高知県'},
                    {value:'福岡県',label:'福岡県'},
                    {value:'佐賀県',label:'佐賀県'},
                    {value:'長崎県',label:'長崎県'},
                    {value:'熊本県',label:'熊本県'},
                    {value:'大分県',label:'大分県'},
                    {value:'宮崎県',label:'宮崎県'},
                    {value:'鹿児島県',label:'鹿児島県'},
                    {value:'沖縄県',label:'沖縄県'},]
};



// export function getindustryList() {
//     return industryList;
//   }